tokens = (
        'BASETYPE',
        'STRUCT',
        'UNIOP',
        'BIOP',
        'NUMBERI',
        'NUMBERF',
        'NUMBERU',
        'SYMBOL',
        'CHAR',
        'STRING',
        'IF',
        'ELSE',
        'RETURN',
        'WHILE',
        'FOR',
        'RAW',
)
