tokens = (
        'TYPE',
        'UNIOP',
        'BIOP',
        'NUMBERI',
        'NUMBERF',
        'NUMBERU',
        'SYMBOL',
        'CHAR',
        'STRING',
        'IF',
        'ELSE',
        'RETURN',
        'WHILE',
        'FOR',
        'READREG',
        'WRITEREG',
)
